name: 📖 Historia de Usuario
description: Template para reportar historias de usuario con criterios de aceptación y tareas de desarrollo
title: "[HU]: "
labels: ["Funcionalidad"]
body:
  - type: markdown
    attributes:
      value: |
        ## Historia de Usuario
        > Describe la funcionalidad desde la perspectiva del usuario final. El **"Para"** debe entregar valor y el **Como** debe ser un interesado/stakeholder.

  - type: textarea
    id: user-story
    attributes:
      label: Contenido de la Historia
      description: |
        **Como** usuario **Quiero** lograr algo **Para** obtener un beneficio
      value: |
        **Como** **Quiero** **Para**
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## Criterios de Aceptación
        > Define las condiciones mínimas para que esta historia se considere "terminada".

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Lista de Criterios
      description: Define las condiciones que deben cumplirse.
      value: |
        - [ ] Criterio 1
        - [ ] Criterio 2
        - [ ] Criterio 3
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Tareas
        > Desglose técnico de los pasos necesarios para la implementación.

  - type: textarea
    id: dev-tasks
    attributes:
      label: Lista de Tareas
      description: Lista de tareas técnicas para implementar la historia.
      value: |
        - [ ] Tarea 1
        - [ ] Tarea 2
        - [ ] Tarea 3
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Notas adicionales
        > Contexto extra, enlaces, documentación técnica o dependencias.

  - type: textarea
    id: notes
    attributes:
      label: Notas
      placeholder: "Ej: Revisar el componente Button en la librería de UI..."
    validations:
      required: false
