name: 🛠️ Tarea tecnica
description: Template para redactar tareas tecnicas que necesitan cumplirse para continuar con el desarrollo
title: "[TASK]: "
labels: ["Tarea Tecnica"]
body:
  # --- SECCIÓN OBJETIVO ---
  - type: markdown
    attributes:
      value: |
        ## Objetivo
        > ¿Qué se busca lograr con esta tarea? Explica el propósito técnico o la necesidad de esta implementación.

  - type: textarea
    id: objective
    attributes:
      label: Descripción del Objetivo
      description: |
        **Ej:** Inicializar el proyecto asegurando que la base cumpla con los estándares de estilo y accesibilidad definidos.
    validations:
      required: true
  
  # --- SECCIÓN TAREAS ---
  - type: markdown
    attributes:
      value: |
        ---
        ## Tareas
        > Lista detallada de las subtareas técnicas a completar.

  - type: textarea
    id: dev-tasks
    attributes:
      label: Listado de subtareas
      description: Pasos técnicos específicos.
      value: |
        - [ ] Tarea 1
        - [ ] Tarea 2
        - [ ] Tarea 3
    validations:
      required: true

  # --- SECCIÓN NOTAS ---
  - type: markdown
    attributes:
      value: |
        ## Notas Adicionales
        > Contexto extra, tecnicismos, documentación de referencia o consideraciones especiales.

  - type: textarea
    id: notes
    attributes:
      label: Notas y Referencias
      placeholder: "Añade contexto, referencias, tecnicismos..."
    validations:
      required: false
