name: 📋 Dev Report
description: Template para reportar historias de usuario con criterios de aceptación y tareas de desarrollo
title: "[DEV]: "
labels: ["dev", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        ## Historia de Usuario
        Describe la funcionalidad desde la perspectiva del usuario final.

  - type: input
    id: user-role
    attributes:
      label: Como
      description: ¿Qué tipo de usuario eres? (ej. visitante, administrador, colaborador)
      placeholder: "visitante"
    validations:
      required: true

  - type: textarea
    id: user-want
    attributes:
      label: Quiero
      description: ¿Qué funcionalidad o capacidad deseas?
      placeholder: "entender de inmediato la propuesta de valor y tener un camino claro para unirme"
    validations:
      required: true

  - type: textarea
    id: user-goal
    attributes:
      label: Para
      description: ¿Cuál es el objetivo o beneficio que buscas?
      placeholder: "convertir mi interés en una acción concreta (unirme/colaborar) sin fricción ni dudas"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## Criterios de Aceptación
        Define las condiciones que deben cumplirse para considerar completada esta historia.

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Criterios de Aceptación
      description: Lista los criterios que deben cumplirse (usa formato `- [ ]` para checkboxes)
      placeholder: "- [ ] Criterio 1\n- [ ] Criterio 2\n- [ ] Criterio 3"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ---
        ## Tareas de Desarrollo

  - type: textarea
    id: dev-tasks
    attributes:
      label: Tareas
      description: Lista de tareas técnicas para implementar la historia (usa formato `- [ ]` para checkboxes)
      placeholder: "- [ ] Tarea 1\n- [ ] Tarea 2\n- [ ] Tarea 3"
    validations:
      required: true

  - type: textarea
    id: technical-details
    attributes:
      label: Detalles Técnicos
      description: Información técnica relevante, tecnologías, componentes, o consideraciones especiales
      placeholder: "Componentes a usar: HeroSection.astro\nDiseño: Penpot (Hero/Nav/Foot)\nLinks: Discord (permanente), Repo"
    validations:
      required: false

  - type: textarea
    id: notes
    attributes:
      label: Notas Adicionales
      description: Cualquier información adicional o contexto relevante
      placeholder: "Añade contexto, referencias, o consideraciones especiales..."
    validations:
      required: false
